# Generated by Django 4.2.7 on 2026-06-24 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=120)),
                ('tipo', models.CharField(default='Teoría', max_length=40)),
                ('total_sesiones', models.IntegerField()),
                ('duracion_sesion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_curso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloque de curso',
                'verbose_name_plural': 'Bloques de curso',
                'ordering': ['curso', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('falta', 'Falta')], default='presente', max_length=10)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencias.bloquecurso')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha'],
            },
        ),
    ]
